version: "3.9"
services:
  worker:
    build: ./services/worker
    env_file: .env
    volumes:
      - ./data:/app/data
    command: ["python","etl/main.py"]
  api:
    build: ./services/api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
  dashboard:
    build: ./services/dashboard
    env_file: .env
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    command: ["streamlit","run","app.py","--server.port=8501","--server.address=0.0.0.0"]
